# SeamlessM4T-v2 — Rigorous Validation

End-to-end validation of **SeamlessM4T-v2** inside the evaluator, across multiple settings:

1. **Audio synthesis** with M4T / MMS TTS — including the per-language (`language`) parameter.
2. **ASR backends** — Whisper vs SeamlessM4T ASR vs SeamlessM4T speech→English *translation*.
3. **Retrieval strategies** with M4T ASR — dense vs hybrid (RRF) vs reranker.
4. **Fusion retrieval** — `audio_text_retrieval` fusing an audio embedder with a text embedder.
5. **SONAR shared-space retrieval** — zero-shot audio→text in one 1024-d space.

Dataset: bundled `data/pubmed_qa_small/` (text questions → TTS audio → pipeline). Everything
runs on CPU with a small `TRACE_LIMIT`; bump it (and switch devices to CUDA) for a real run.

> SeamlessM4T-v2-large is a ~2.3 GB download; the first ASR/TTS cell will fetch it.

## 1. Install

In [1]:
# Install evaluator from repo root
%pip install -q -e '..'
# M4T ASR/TTS + audio IO
%pip install -q transformers torch sentencepiece soundfile

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.

## 2. Setup

Paths, a config builder, and a `run_setting` helper that runs one configuration and collects metrics.

In [2]:
from pathlib import Path
import pandas as pd
from evaluator import EvaluationConfig, run_evaluation

DATA_DIR = Path('data/pubmed_qa_small')
Q = str(DATA_DIR / 'questions.json')
C = str(DATA_DIR / 'corpus.json')
AUDIO_DIR = str(DATA_DIR / 'audio')
OUT_DIR = 'm4t_validation_out'

TRACE_LIMIT = 5          # raise for rigor (full set has 20 questions)
DEVICE = 'cpu'           # set 'cuda:0' if you have a GPU
EVAL_TTS = 'mms'         # fast TTS used to create ASR input audio

ROWS = []

def make_config(name, model, vector_db=None, features=None, trace_limit=TRACE_LIMIT):
    feats = {'audio_synthesis': {'enabled': True, 'provider': EVAL_TTS, 'language': 'en',
                                 'sample_rate': 16000, 'output_dir': AUDIO_DIR}}
    for k, v in (features or {}).items():
        feats[k] = {**feats.get(k, {}), **v} if isinstance(v, dict) else v
    return EvaluationConfig.from_dict({
        'experiment_name': name,
        'output_dir': OUT_DIR,
        'model': {'asr_device': DEVICE, 'text_emb_device': DEVICE, 'audio_emb_device': DEVICE, **model},
        'data': {'dataset_name': 'pubmed_qa', 'questions_path': Q, 'corpus_path': C,
                 'batch_size': 4, 'trace_limit': trace_limit, 'strict_validation': False},
        'vector_db': {'type': 'inmemory', 'k': 10, **(vector_db or {})},
        'features': feats,
        'cache': {'enabled': True},
    })

METRICS = ['WER', 'CER', 'MRR', 'MAP', 'Recall@1', 'Recall@5', 'NDCG@10']

def run_setting(label, model, mode='asr_text_retrieval', vector_db=None, features=None, trace_limit=TRACE_LIMIT):
    cfg = make_config(label, {'pipeline_mode': mode, **model}, vector_db, features, trace_limit)
    res = run_evaluation(cfg)
    row = {'setting': label}
    for k in METRICS:
        try:
            v = res.get_metric(k)
        except Exception:
            v = None
        if v is not None:
            row[k] = round(float(v), 4)
    ROWS.append(row)
    print(label, '->', {k: row[k] for k in row if k != 'setting'})
    return res

## 3. Audio synthesis + the `language` parameter

The evaluator synthesizes audio for text-only questions. `AudioSynthesisConfig.language` sets the
TTS language; each question's own `language` field (if present) overrides it, so multilingual
datasets synthesize in the right language. Here we synthesize the same idea in **English** and
**Polish** and listen to both.

In [3]:
from evaluator.config import AudioSynthesisConfig
from evaluator.pipeline.audio.synthesis import AudioSynthesizer
from IPython.display import Audio, display

samples = [
    ('en', 'Does aspirin reduce the risk of heart attack?'),
    ('pl', 'Czy aspiryna zmniejsza ryzyko zawalu serca?'),
]
for lang, text in samples:
    cfg = AudioSynthesisConfig(enabled=True, provider='mms', language=lang, sample_rate=16000)
    audio = AudioSynthesizer(cfg).synthesize(text)
    print(f'[{lang}] {text}')
    display(Audio(audio, rate=16000))

[en] Does aspirin reduce the risk of heart attack?

[pl] Czy aspiryna zmniejsza ryzyko zawalu serca?

In [4]:
# Optional: the same with the SeamlessM4T-v2 TTS provider (heavier; downloads the M4T model).
RUN_M4T_TTS = False
if RUN_M4T_TTS:
    cfg = AudioSynthesisConfig(enabled=True, provider='m4t', language='en', sample_rate=16000)
    audio = AudioSynthesizer(cfg).synthesize('Does aspirin reduce the risk of heart attack?')
    display(Audio(audio, rate=16000))

## 4. Experiment A — ASR backends

Same retrieval (LaBSE, dense), different ASR front-ends:

- `whisper` (tiny) — baseline
- `seamless_m4t` — SeamlessM4T-v2 ASR (English transcription)
- `seamless_m4t` + `tgt_lang=eng` — speech→English **translation** used as ASR

Lower WER and higher MRR are better. (English audio here, so ASR and translate behave similarly;
the translate setting shines on non-English audio.)

In [5]:
run_setting('whisper-tiny + labse', {'asr_model_type': 'whisper', 'asr_size': 'tiny', 'text_emb_model_type': 'labse'})
run_setting('m4t-asr + labse', {'asr_model_type': 'seamless_m4t', 'text_emb_model_type': 'labse'})
run_setting('m4t-translate(eng) + labse', {'asr_model_type': 'seamless_m4t', 'asr_params': {'tgt_lang': 'eng'}, 'text_emb_model_type': 'labse'})
pd.DataFrame(ROWS).set_index('setting')

INFO | evaluator | Logging initialized. Log file: logs/2026-06-03_20-59-54_whisper-tiny + labse.log
INFO | evaluator.services.model_services | service.start label=asr:whisper@cpu load_time=2.88s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.52s
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: ASR + Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=asr_text_retrieval levels=[['asr'], ['text_embedding'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: ASR Transcription
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.pipeline.asr_pipeline | Processing 5 samples through ASR...

ASR Processing: 100%|██████████| 2/2 [00:12<00:00,  6.34s/it]

INFO | evaluator.pipeline.asr_pipeline | ASR Dataset Processing completed in 12.68s
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 2 batches processed
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ASR Phase complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 2: Text Embedding (from ASR)
INFO | evaluator.evaluation.phased | ==================================================

INFO | evaluator.evaluation.phased | Embedding Phase completed in 0.02s
INFO | evaluator.evaluation.phased | Text Embedding Phase complete: 5 embeddings
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | RETRIEVAL DEBUG SAMPLE (first 3 queries):
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased |
Query 1:
INFO | evaluator.evaluation.phased |   ASR query text:        ' Do mitochondria play a role in remodelling lace plant leaves during progren? Sell death.'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?'
INFO | evaluator.evaluation.phased |   Expected doc:  [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Apon'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3056 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.0774 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.0756 | [26037986] 'Emergency surgery is associated with poorer outcomes and higher mortality with r'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0592 | [25957366] 'Electronic health records have the potential to facilitate family history use by'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0267 | [17096624] 'To examine patterns of knowledge and attitudes among adults aged>65 years unvacc'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3056)
INFO | evaluator.evaluation.phased |
Query 2:
INFO | evaluator.evaluation.phased |   ASR query text:        ' Landolt can snow in your cutie differences in Stratismus ambiolia.'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Landolt C and snellen e acuity: differences in strabismus amblyopia?'
INFO | evaluator.evaluation.phased |   Expected doc:  [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The ability to recognize '
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✗] Score: 0.1481 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     2. [✓] Score: 0.1415 | [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The a'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.0177 | [22694248] 'Although the retroperitoneal approach has been the preferred choice for open uro'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0138 | [18239988] 'Specific markers for differentiation of nonalcoholic (NASH) from alcoholic steat'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0125 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 2 (score: 0.1415)
INFO | evaluator.evaluation.phased |
Query 3:
INFO | evaluator.evaluation.phased |   ASR query text:        ' Syncope during bathing in infants, a pediatric form of water induced derticaria.'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Syncope during bathing in infants, a pediatric form of water-induced urticaria?'
INFO | evaluator.evaluation.phased |   Expected doc:  [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem in pediatric practi'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.2685 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1437 | [23831910] 'From March 2007 to January 2011, 88 DBE procedures were performed on 66 patients'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.0823 | [10966337] 'We evaluated the usefulness of a short stay or 23-hour ward in a pediatric unit '
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0620 | [18847643] 'Trauma patients who require therapeutic anticoagulation pose a difficult treatme'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0575 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.2685)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | ASR Metrics - WER: 0.2853, CER: 0.0924
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 0.9000
INFO | evaluator.evaluation.phased |   MAP: 0.9000
INFO | evaluator.evaluation.phased |   Recall@1: 0.8000
INFO | evaluator.evaluation.phased |   NDCG@1: 0.8000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 0.9262
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 0.9262
INFO | evaluator.evaluation.phased | Stage latency — asr=12.9s embed=0.0s retrieve=0.0s total=12.9s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True
INFO | evaluator.services.model_services | service.stop label=asr:whisper@cpu
INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
whisper-tiny + labse -> {'WER': 0.2853, 'CER': 0.0924, 'MRR': 0.9, 'MAP': 0.9, 'Recall@1': 0.8, 'Recall@5': 1.0, 'NDCG@10': 0.9262}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.services.model_services | service.start label=asr:seamless_m4t@cpu load_time=7.55s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.13s
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: ASR + Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=asr_text_retrieval levels=[['asr'], ['text_embedding'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: ASR Transcription
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.pipeline.asr_pipeline | Processing 5 samples through ASR...

ASR Processing: 100%|██████████| 2/2 [00:09<00:00,  4.99s/it]

INFO | evaluator.pipeline.asr_pipeline | ASR Dataset Processing completed in 9.99s
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 2 batches processed

INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ASR Phase complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 2: Text Embedding (from ASR)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding Phase completed in 0.02s
INFO | evaluator.evaluation.phased | Text Embedding Phase complete: 5 embeddings
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | RETRIEVAL DEBUG SAMPLE (first 3 queries):
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased |
Query 1:
INFO | evaluator.evaluation.phased |   ASR query text:        'do mittachandria play a role in remodeling lace plant leaves during progrm cell death'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?'
INFO | evaluator.evaluation.phased |   Expected doc:  [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Apon'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3191 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1331 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1087 | [26037986] 'Emergency surgery is associated with poorer outcomes and higher mortality with r'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0685 | [25957366] 'Electronic health records have the potential to facilitate family history use by'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0581 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3191)
INFO | evaluator.evaluation.phased |
Query 2:
INFO | evaluator.evaluation.phased |   ASR query text:        'landolt can know any acute differences in strabismus ambliolia'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Landolt C and snellen e acuity: differences in strabismus amblyopia?'
INFO | evaluator.evaluation.phased |   Expected doc:  [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The ability to recognize '
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✗] Score: 0.2343 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     2. [✓] Score: 0.2269 | [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The a'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1695 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1651 | [18239988] 'Specific markers for differentiation of nonalcoholic (NASH) from alcoholic steat'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.1270 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 2 (score: 0.2269)
INFO | evaluator.evaluation.phased |
Query 3:
INFO | evaluator.evaluation.phased |   ASR query text:        'syncope during bathing in infants a pediatric form of water induced urticaria'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Syncope during bathing in infants, a pediatric form of water-induced urticaria?'
INFO | evaluator.evaluation.phased |   Expected doc:  [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem in pediatric practi'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3519 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1663 | [10966337] 'We evaluated the usefulness of a short stay or 23-hour ward in a pediatric unit '
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1383 | [23831910] 'From March 2007 to January 2011, 88 DBE procedures were performed on 66 patients'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1173 | [18847643] 'Trauma patients who require therapeutic anticoagulation pose a difficult treatme'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0942 | [26852225] 'Anchoring vignettes are brief texts describing a hypothetical character who illu'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3519)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | ASR Metrics - WER: 0.3948, CER: 0.1075
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 0.9000
INFO | evaluator.evaluation.phased |   MAP: 0.9000
INFO | evaluator.evaluation.phased |   Recall@1: 0.8000
INFO | evaluator.evaluation.phased |   NDCG@1: 0.8000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 0.9262
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 0.9262
INFO | evaluator.evaluation.phased | Stage latency — asr=10.2s embed=0.0s retrieve=0.0s total=10.2s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True
INFO | evaluator.services.model_services | service.stop label=asr:seamless_m4t@cpu
INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
m4t-asr + labse -> {'WER': 0.3948, 'CER': 0.1075, 'MRR': 0.9, 'MAP': 0.9, 'Recall@1': 0.8, 'Recall@5': 1.0, 'NDCG@10': 0.9262}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.services.model_services | service.start label=asr:seamless_m4t@cpu load_time=7.14s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.09s
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: ASR + Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=asr_text_retrieval levels=[['asr'], ['text_embedding'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: ASR Transcription
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.pipeline.asr_pipeline | Processing 5 samples through ASR...

ASR Processing: 100%|██████████| 2/2 [00:10<00:00,  5.09s/it]

INFO | evaluator.pipeline.asr_pipeline | ASR Dataset Processing completed in 10.18s
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 2 batches processed

INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ASR Phase complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 2: Text Embedding (from ASR)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding Phase completed in 0.02s
INFO | evaluator.evaluation.phased | Text Embedding Phase complete: 5 embeddings
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | RETRIEVAL DEBUG SAMPLE (first 3 queries):
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased |
Query 1:
INFO | evaluator.evaluation.phased |   ASR query text:        'do mittachandria play a role in remodeling lace plant leaves during progrm cell death'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?'
INFO | evaluator.evaluation.phased |   Expected doc:  [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Apon'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3191 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1331 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1087 | [26037986] 'Emergency surgery is associated with poorer outcomes and higher mortality with r'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0685 | [25957366] 'Electronic health records have the potential to facilitate family history use by'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0581 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3191)
INFO | evaluator.evaluation.phased |
Query 2:
INFO | evaluator.evaluation.phased |   ASR query text:        'landolt can know any acute differences in strabismus ambliolia'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Landolt C and snellen e acuity: differences in strabismus amblyopia?'
INFO | evaluator.evaluation.phased |   Expected doc:  [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The ability to recognize '
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✗] Score: 0.2343 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     2. [✓] Score: 0.2269 | [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The a'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1695 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1651 | [18239988] 'Specific markers for differentiation of nonalcoholic (NASH) from alcoholic steat'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.1270 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 2 (score: 0.2269)
INFO | evaluator.evaluation.phased |
Query 3:
INFO | evaluator.evaluation.phased |   ASR query text:        'syncope during bathing in infants a pediatric form of water induced urticaria'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Syncope during bathing in infants, a pediatric form of water-induced urticaria?'
INFO | evaluator.evaluation.phased |   Expected doc:  [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem in pediatric practi'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3519 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1663 | [10966337] 'We evaluated the usefulness of a short stay or 23-hour ward in a pediatric unit '
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1383 | [23831910] 'From March 2007 to January 2011, 88 DBE procedures were performed on 66 patients'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1173 | [18847643] 'Trauma patients who require therapeutic anticoagulation pose a difficult treatme'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0942 | [26852225] 'Anchoring vignettes are brief texts describing a hypothetical character who illu'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3519)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | ASR Metrics - WER: 0.3948, CER: 0.1075
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 0.9000
INFO | evaluator.evaluation.phased |   MAP: 0.9000
INFO | evaluator.evaluation.phased |   Recall@1: 0.8000
INFO | evaluator.evaluation.phased |   NDCG@1: 0.8000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 0.9262
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 0.9262
INFO | evaluator.evaluation.phased | Stage latency — asr=10.4s embed=0.0s retrieve=0.0s total=10.4s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True
INFO | evaluator.services.model_services | service.stop label=asr:seamless_m4t@cpu
INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
m4t-translate(eng) + labse -> {'WER': 0.3948, 'CER': 0.1075, 'MRR': 0.9, 'MAP': 0.9, 'Recall@1': 0.8, 'Recall@5': 1.0, 'NDCG@10': 0.9262}

,WER,CER,MRR,MAP,Recall@1,Recall@5,NDCG@10
setting,,,,,,,
whisper-tiny + labse,0.2853,0.0924,0.9,0.9,0.8,1.0,0.9262
m4t-asr + labse,0.3948,0.1075,0.9,0.9,0.8,1.0,0.9262
m4t-translate(eng) + labse,0.3948,0.1075,0.9,0.9,0.8,1.0,0.9262

## 5. Experiment B — retrieval strategies with M4T ASR

Fix the front-end to SeamlessM4T ASR + LaBSE; vary retrieval:

- **dense** — embedding similarity
- **hybrid (RRF)** — dense + BM25 fused with reciprocal-rank fusion
- **dense + reranker** — cross-encoder reranks top candidates (downloads a small cross-encoder)

In [6]:
M4T = {'asr_model_type': 'seamless_m4t', 'text_emb_model_type': 'labse'}

run_setting('m4t + dense', M4T, vector_db={'retrieval_mode': 'dense'})
run_setting('m4t + hybrid(rrf)', M4T, vector_db={'retrieval_mode': 'hybrid', 'hybrid_fusion_method': 'rrf'})

RUN_RERANKER = True  # set False to skip the cross-encoder download
if RUN_RERANKER:
    run_setting('m4t + dense + reranker', M4T, vector_db={
        'retrieval_mode': 'dense', 'reranker_enabled': True, 'reranker_mode': 'cross_encoder',
        'reranker_model': 'cross-encoder/ms-marco-MiniLM-L-6-v2', 'reranker_top_k': 10,
    })
pd.DataFrame(ROWS).set_index('setting')

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.services.model_services | service.start label=asr:seamless_m4t@cpu load_time=6.97s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.07s
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: ASR + Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=asr_text_retrieval levels=[['asr'], ['text_embedding'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: ASR Transcription
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.pipeline.asr_pipeline | Processing 5 samples through ASR...

ASR Processing: 100%|██████████| 2/2 [00:09<00:00,  4.87s/it]

INFO | evaluator.pipeline.asr_pipeline | ASR Dataset Processing completed in 9.75s
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 2 batches processed

INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ASR Phase complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 2: Text Embedding (from ASR)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding Phase completed in 0.02s
INFO | evaluator.evaluation.phased | Text Embedding Phase complete: 5 embeddings
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | RETRIEVAL DEBUG SAMPLE (first 3 queries):
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased |
Query 1:
INFO | evaluator.evaluation.phased |   ASR query text:        'do mittachandria play a role in remodeling lace plant leaves during progrm cell death'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?'
INFO | evaluator.evaluation.phased |   Expected doc:  [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Apon'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3191 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1331 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1087 | [26037986] 'Emergency surgery is associated with poorer outcomes and higher mortality with r'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0685 | [25957366] 'Electronic health records have the potential to facilitate family history use by'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0581 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3191)
INFO | evaluator.evaluation.phased |
Query 2:
INFO | evaluator.evaluation.phased |   ASR query text:        'landolt can know any acute differences in strabismus ambliolia'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Landolt C and snellen e acuity: differences in strabismus amblyopia?'
INFO | evaluator.evaluation.phased |   Expected doc:  [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The ability to recognize '
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✗] Score: 0.2343 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     2. [✓] Score: 0.2269 | [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The a'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1695 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1651 | [18239988] 'Specific markers for differentiation of nonalcoholic (NASH) from alcoholic steat'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.1270 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 2 (score: 0.2269)
INFO | evaluator.evaluation.phased |
Query 3:
INFO | evaluator.evaluation.phased |   ASR query text:        'syncope during bathing in infants a pediatric form of water induced urticaria'
INFO | evaluator.evaluation.phased |   Ground truth question: 'Syncope during bathing in infants, a pediatric form of water-induced urticaria?'
INFO | evaluator.evaluation.phased |   Expected doc:  [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem in pediatric practi'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3519 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1663 | [10966337] 'We evaluated the usefulness of a short stay or 23-hour ward in a pediatric unit '
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1383 | [23831910] 'From March 2007 to January 2011, 88 DBE procedures were performed on 66 patients'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1173 | [18847643] 'Trauma patients who require therapeutic anticoagulation pose a difficult treatme'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0942 | [26852225] 'Anchoring vignettes are brief texts describing a hypothetical character who illu'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3519)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | ASR Metrics - WER: 0.3948, CER: 0.1075
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 0.9000
INFO | evaluator.evaluation.phased |   MAP: 0.9000
INFO | evaluator.evaluation.phased |   Recall@1: 0.8000
INFO | evaluator.evaluation.phased |   NDCG@1: 0.8000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 0.9262
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 0.9262
INFO | evaluator.evaluation.phased | Stage latency — asr=10.0s embed=0.0s retrieve=0.0s total=10.0s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True
INFO | evaluator.services.model_services | service.stop label=asr:seamless_m4t@cpu
INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
m4t + dense -> {'WER': 0.3948, 'CER': 0.1075, 'MRR': 0.9, 'MAP': 0.9, 'Recall@1': 0.8, 'Recall@5': 1.0, 'NDCG@10': 0.9262}

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.services.model_services | service.start label=asr:seamless_m4t@cpu load_time=7.23s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.13s
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: ASR + Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=asr_text_retrieval levels=[['asr'], ['text_embedding'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: ASR Transcription
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.pipeline.asr_pipeline | Processing 5 samples through ASR...

ASR Processing: 100%|██████████| 2/2 [00:09<00:00,  4.92s/it]

INFO | evaluator.pipeline.asr_pipeline | ASR Dataset Processing completed in 9.85s
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 2 batches processed

INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ASR Phase complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 2: Text Embedding (from ASR)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding Phase completed in 0.02s
INFO | evaluator.evaluation.phased | Text Embedding Phase complete: 5 embeddings
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | Skipping dense-only debug re-search for current retrieval mode/reranker
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | ASR Metrics - WER: 0.3948, CER: 0.1075
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 0.8400
INFO | evaluator.evaluation.phased |   MAP: 0.8400
INFO | evaluator.evaluation.phased |   Recall@1: 0.8000
INFO | evaluator.evaluation.phased |   NDCG@1: 0.8000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 0.8774
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 0.8774
INFO | evaluator.evaluation.phased | Stage latency — asr=10.1s embed=0.0s retrieve=0.0s total=10.1s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True
INFO | evaluator.services.model_services | service.stop label=asr:seamless_m4t@cpu
INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
m4t + hybrid(rrf) -> {'WER': 0.3948, 'CER': 0.1075, 'MRR': 0.84, 'MAP': 0.84, 'Recall@1': 0.8, 'Recall@5': 1.0, 'NDCG@10': 0.8774}
INFO | evaluator.models.retrieval.rag.reranker | Loaded CrossEncoder reranker: cross-encoder/ms-marco-MiniLM-L-6-v2
INFO | evaluator.services.model_services | service.start label=reranker:cross_encoder@None load_time=1.37s

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.services.model_services | service.start label=asr:seamless_m4t@cpu load_time=7.22s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.17s
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore, cross-encoder reranker: cross-encoder/ms-marco-MiniLM-L-6-v2
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: ASR + Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=asr_text_retrieval levels=[['asr'], ['text_embedding'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: ASR Transcription
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.pipeline.asr_pipeline | Processing 5 samples through ASR...

ASR Processing: 100%|██████████| 2/2 [00:09<00:00,  4.98s/it]

INFO | evaluator.pipeline.asr_pipeline | ASR Dataset Processing completed in 9.95s
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 2 batches processed
INFO | evaluator.pipeline.asr_pipeline | ASR processing complete: 5 transcriptions
INFO | evaluator.evaluation.phased | ASR Phase complete: 5 transcriptions

INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 2: Text Embedding (from ASR)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding Phase completed in 0.02s
INFO | evaluator.evaluation.phased | Text Embedding Phase complete: 5 embeddings
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.61s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | Skipping dense-only debug re-search for current retrieval mode/reranker
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | ASR Metrics - WER: 0.3948, CER: 0.1075
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 1.0000
INFO | evaluator.evaluation.phased |   MAP: 1.0000
INFO | evaluator.evaluation.phased |   Recall@1: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@1: 1.0000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 1.0000
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 1.0000
INFO | evaluator.evaluation.phased | Stage latency — asr=10.2s embed=0.0s retrieve=0.6s total=10.8s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True
INFO | evaluator.services.model_services | service.stop label=asr:seamless_m4t@cpu
INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
INFO | evaluator.services.model_services | service.stop label=reranker:cross_encoder@None
m4t + dense + reranker -> {'WER': 0.3948, 'CER': 0.1075, 'MRR': 1.0, 'MAP': 1.0, 'Recall@1': 1.0, 'Recall@5': 1.0, 'NDCG@10': 1.0}

,WER,CER,MRR,MAP,Recall@1,Recall@5,NDCG@10
setting,,,,,,,
whisper-tiny + labse,0.2853,0.0924,0.90,0.90,0.8,1.0,0.9262
m4t-asr + labse,0.3948,0.1075,0.90,0.90,0.8,1.0,0.9262
m4t-translate(eng) + labse,0.3948,0.1075,0.90,0.90,0.8,1.0,0.9262
m4t + dense,0.3948,0.1075,0.90,0.90,0.8,1.0,0.9262
m4t + hybrid(rrf),0.3948,0.1075,0.84,0.84,0.8,1.0,0.8774
m4t + dense + reranker,0.3948,0.1075,1.00,1.00,1.0,1.0,1.0000

## 6. Experiment C — fusion retrieval (`audio_text_retrieval`)

Cross-modal fusion: embed the **audio** query (HuBERT, pretrained) and the **text** corpus
(LaBSE), then fuse query representations with `embedding_fusion`. We sweep `audio_weight`.

> HuBERT is used here because it needs no training. For an M4T-native audio embedder use
> `attention_pool_m4t` (needs a trained projection head) or the SONAR speech encoder
> (`sonar_speech`) shown in the next section.

In [7]:
for aw in (0.3, 0.5, 0.7):
    run_setting(
        f'fusion hubert+labse (audio_w={aw})',
        {'audio_emb_model_type': 'hubert', 'audio_emb_dim': 768, 'text_emb_model_type': 'labse'},
        mode='audio_text_retrieval',
        features={'embedding_fusion': {'enabled': True, 'fusion_method': 'weighted',
                                       'audio_weight': aw, 'text_weight': round(1 - aw, 2)}},
    )
pd.DataFrame(ROWS).set_index('setting')

INFO | evaluator.services.model_services | service.start label=audio_embedding:hubert@cpu load_time=1.05s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.09s
INFO | evaluator.pipeline.audio_embedding_pipeline | AudioEmbedding pipeline initialized with model: HuBERTAudioModel - model:facebook/hubert-base-ls960 - pooling:mean - dim:768
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: Audio-to-Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=audio_text_retrieval levels=[['audio_embedding', 'text_embedding'], ['fusion'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: Audio Embedding
INFO | evaluator.evaluation.phased | ==================================================

Audio embedding:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.pipeline.audio_embedding_pipeline | Audio embedding cache: 4/4 hits
INFO | evaluator.pipeline.audio_embedding_pipeline | Audio embedding cache: 1/1 hits

Audio embedding: 100%|██████████| 2/2 [00:00<00:00, 79.27it/s]

INFO | evaluator.evaluation.phased | Audio Embedding Phase completed in 0.03s
INFO | evaluator.evaluation.phased | Audio Embedding Phase complete: 5 audio embeddings
INFO | evaluator.evaluation.phased | Audio embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Audio embedding stats - mean: 0.0013, std: 0.0361
INFO | evaluator.evaluation.phased | Audio embedding norms - mean: 1.0000
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1.5: Text Embedding & Fusion
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Text Embedding for Fusion completed in 0.02s
INFO | evaluator.evaluation.phased | Text embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Text embedding stats - mean: -0.0106, std: 0.0345
INFO | evaluator.models.retrieval.embedding_fusion | Fusion config validated: method=weighted, audio_dim=768, text_dim=768
INFO | evaluator.evaluation.phased | Embedding Fusion completed in 0.00s
INFO | evaluator.evaluation.phased | Fused embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Fused embedding stats - mean: -0.0094, std: 0.0348
INFO | evaluator.evaluation.phased | Fused embedding norms - mean: 1.0000
INFO | evaluator.evaluation.phased | Using fused embeddings for retrieval (method: weighted)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | RETRIEVAL DEBUG SAMPLE (first 3 queries):
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased |
Query 1:
INFO | evaluator.evaluation.phased |   ASR query text:        'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?'
INFO | evaluator.evaluation.phased |   Expected doc:  [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Apon'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3336 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1560 | [25957366] 'Electronic health records have the potential to facilitate family history use by'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1324 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1291 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.1111 | [17096624] 'To examine patterns of knowledge and attitudes among adults aged>65 years unvacc'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3336)
INFO | evaluator.evaluation.phased |
Query 2:
INFO | evaluator.evaluation.phased |   ASR query text:        'Landolt C and snellen e acuity: differences in strabismus amblyopia?'
INFO | evaluator.evaluation.phased |   Expected doc:  [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The ability to recognize '
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.3537 | [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The a'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.2632 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1866 | [18239988] 'Specific markers for differentiation of nonalcoholic (NASH) from alcoholic steat'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1741 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.1343 | [25432938] 'The objective of the current study is to determine to what extent the reduction '
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.3537)
INFO | evaluator.evaluation.phased |
Query 3:
INFO | evaluator.evaluation.phased |   ASR query text:        'Syncope during bathing in infants, a pediatric form of water-induced urticaria?'
INFO | evaluator.evaluation.phased |   Expected doc:  [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem in pediatric practi'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.2758 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1225 | [10966337] 'We evaluated the usefulness of a short stay or 23-hour ward in a pediatric unit '
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1119 | [23831910] 'From March 2007 to January 2011, 88 DBE procedures were performed on 66 patients'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0764 | [18847643] 'Trauma patients who require therapeutic anticoagulation pose a difficult treatme'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0683 | [26852225] 'Anchoring vignettes are brief texts describing a hypothetical character who illu'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.2758)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding alignment — cosine mean=-0.0314 std=0.0152
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 1.0000
INFO | evaluator.evaluation.phased |   MAP: 1.0000
INFO | evaluator.evaluation.phased |   Recall@1: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@1: 1.0000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 1.0000
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 1.0000
INFO | evaluator.evaluation.phased | Stage latency — asr=0.0s embed=0.0s retrieve=0.0s total=0.1s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True

INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
INFO | evaluator.services.model_services | service.stop label=audio_embedding:hubert@cpu
fusion hubert+labse (audio_w=0.3) -> {'MRR': 1.0, 'MAP': 1.0, 'Recall@1': 1.0, 'Recall@5': 1.0, 'NDCG@10': 1.0}
INFO | evaluator.services.model_services | service.start label=audio_embedding:hubert@cpu load_time=0.97s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.23s
INFO | evaluator.pipeline.audio_embedding_pipeline | AudioEmbedding pipeline initialized with model: HuBERTAudioModel - model:facebook/hubert-base-ls960 - pooling:mean - dim:768
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: Audio-to-Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=audio_text_retrieval levels=[['audio_embedding', 'text_embedding'], ['fusion'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: Audio Embedding
INFO | evaluator.evaluation.phased | ==================================================

Audio embedding:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.pipeline.audio_embedding_pipeline | Audio embedding cache: 4/4 hits
INFO | evaluator.pipeline.audio_embedding_pipeline | Audio embedding cache: 1/1 hits

Audio embedding: 100%|██████████| 2/2 [00:00<00:00, 83.55it/s]

INFO | evaluator.evaluation.phased | Audio Embedding Phase completed in 0.02s
INFO | evaluator.evaluation.phased | Audio Embedding Phase complete: 5 audio embeddings
INFO | evaluator.evaluation.phased | Audio embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Audio embedding stats - mean: 0.0013, std: 0.0361
INFO | evaluator.evaluation.phased | Audio embedding norms - mean: 1.0000
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1.5: Text Embedding & Fusion
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Text Embedding for Fusion completed in 0.02s
INFO | evaluator.evaluation.phased | Text embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Text embedding stats - mean: -0.0106, std: 0.0345
INFO | evaluator.models.retrieval.embedding_fusion | Fusion config validated: method=weighted, audio_dim=768, text_dim=768
INFO | evaluator.evaluation.phased | Embedding Fusion completed in 0.00s
INFO | evaluator.evaluation.phased | Fused embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Fused embedding stats - mean: -0.0067, std: 0.0355
INFO | evaluator.evaluation.phased | Fused embedding norms - mean: 1.0000
INFO | evaluator.evaluation.phased | Using fused embeddings for retrieval (method: weighted)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | RETRIEVAL DEBUG SAMPLE (first 3 queries):
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased |
Query 1:
INFO | evaluator.evaluation.phased |   ASR query text:        'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?'
INFO | evaluator.evaluation.phased |   Expected doc:  [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Apon'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.2815 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1346 | [25957366] 'Electronic health records have the potential to facilitate family history use by'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1193 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1068 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0903 | [17096624] 'To examine patterns of knowledge and attitudes among adults aged>65 years unvacc'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.2815)
INFO | evaluator.evaluation.phased |
Query 2:
INFO | evaluator.evaluation.phased |   ASR query text:        'Landolt C and snellen e acuity: differences in strabismus amblyopia?'
INFO | evaluator.evaluation.phased |   Expected doc:  [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The ability to recognize '
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.2707 | [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The a'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.2222 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1613 | [18239988] 'Specific markers for differentiation of nonalcoholic (NASH) from alcoholic steat'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1399 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.1274 | [25432938] 'The objective of the current study is to determine to what extent the reduction '
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.2707)
INFO | evaluator.evaluation.phased |
Query 3:
INFO | evaluator.evaluation.phased |   ASR query text:        'Syncope during bathing in infants, a pediatric form of water-induced urticaria?'
INFO | evaluator.evaluation.phased |   Expected doc:  [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem in pediatric practi'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.2297 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.1080 | [10966337] 'We evaluated the usefulness of a short stay or 23-hour ward in a pediatric unit '
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.0903 | [23831910] 'From March 2007 to January 2011, 88 DBE procedures were performed on 66 patients'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0746 | [18847643] 'Trauma patients who require therapeutic anticoagulation pose a difficult treatme'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0654 | [26852225] 'Anchoring vignettes are brief texts describing a hypothetical character who illu'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.2297)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding alignment — cosine mean=-0.0314 std=0.0152
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 1.0000
INFO | evaluator.evaluation.phased |   MAP: 1.0000
INFO | evaluator.evaluation.phased |   Recall@1: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@1: 1.0000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 1.0000
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 1.0000
INFO | evaluator.evaluation.phased | Stage latency — asr=0.0s embed=0.0s retrieve=0.0s total=0.1s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True

INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
INFO | evaluator.services.model_services | service.stop label=audio_embedding:hubert@cpu
fusion hubert+labse (audio_w=0.5) -> {'MRR': 1.0, 'MAP': 1.0, 'Recall@1': 1.0, 'Recall@5': 1.0, 'NDCG@10': 1.0}
INFO | evaluator.services.model_services | service.start label=audio_embedding:hubert@cpu load_time=0.91s
INFO | evaluator.services.model_services | service.start label=text_embedding:labse@cpu load_time=4.13s
INFO | evaluator.pipeline.audio_embedding_pipeline | AudioEmbedding pipeline initialized with model: HuBERTAudioModel - model:facebook/hubert-base-ls960 - pooling:mean - dim:768
INFO | evaluator.pipeline.retrieval_pipeline | Retrieval pipeline initialized with vector store: InMemoryVectorStore
INFO | evaluator.services.evaluation_service | service.startup_policy mode=lazy
INFO | evaluator.services.evaluation_service | Audio synthesis enabled - checking for questions needing synthesis
INFO | evaluator.services.evaluation_service | Synthesizing audio for 5 text question(s) via TTS provider 'mms' (lang=en) -> data/pubmed_qa_small/audio
INFO | evaluator.pipeline.audio.synthesis | TTS cache auto-enabled at: data/pubmed_qa_small/audio/.tts_cache
INFO | evaluator.models.tts.mms_tts | MMS TTS initialized with model: facebook/mms-tts-eng
INFO | evaluator.pipeline.audio.synthesis | Initialized TTS model: mms
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_21645374.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_16418930.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_9488747.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_17208539.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache hit (file): data/pubmed_qa_small/audio/q_10808977.wav
INFO | evaluator.pipeline.audio.synthesis | TTS cache stats: 5/5 hits (100%), 0 synthesized
INFO | evaluator.services.evaluation_service | Audio synthesis complete (5/5 questions)
INFO | evaluator.services.evaluation_service | Loaded cached retrieval index artifacts: vectors=20
INFO | evaluator.pipeline.retrieval_pipeline | Building vector index (20 vectors) completed in 0.00s
INFO | evaluator.evaluation.phased | Evaluation mode: Audio-to-Text Retrieval (Phased)
INFO | evaluator.evaluation.phased | Execution DAG mode=audio_text_retrieval levels=[['audio_embedding', 'text_embedding'], ['fusion'], ['retrieval'], ['metrics']]
INFO | evaluator.evaluation.phased | Dataset size: 5, Batch size: 4, k: 10
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1: Audio Embedding
INFO | evaluator.evaluation.phased | ==================================================

Audio embedding:   0%|          | 0/2 [00:00<?, ?it/s]

INFO | evaluator.pipeline.audio_embedding_pipeline | Audio embedding cache: 4/4 hits
INFO | evaluator.pipeline.audio_embedding_pipeline | Audio embedding cache: 1/1 hits

Audio embedding: 100%|██████████| 2/2 [00:00<00:00, 78.02it/s]

INFO | evaluator.evaluation.phased | Audio Embedding Phase completed in 0.03s
INFO | evaluator.evaluation.phased | Audio Embedding Phase complete: 5 audio embeddings
INFO | evaluator.evaluation.phased | Audio embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Audio embedding stats - mean: 0.0013, std: 0.0361
INFO | evaluator.evaluation.phased | Audio embedding norms - mean: 1.0000
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 1.5: Text Embedding & Fusion
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Text Embedding for Fusion completed in 0.02s
INFO | evaluator.evaluation.phased | Text embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Text embedding stats - mean: -0.0106, std: 0.0345
INFO | evaluator.models.retrieval.embedding_fusion | Fusion config validated: method=weighted, audio_dim=768, text_dim=768
INFO | evaluator.evaluation.phased | Embedding Fusion completed in 0.00s
INFO | evaluator.evaluation.phased | Fused embedding shape: (5, 768)
INFO | evaluator.evaluation.phased | Fused embedding stats - mean: -0.0030, std: 0.0360
INFO | evaluator.evaluation.phased | Fused embedding norms - mean: 1.0000
INFO | evaluator.evaluation.phased | Using fused embeddings for retrieval (method: weighted)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 3: Retrieval
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Retrieval Phase completed in 0.00s
INFO | evaluator.evaluation.phased | Retrieval Phase complete: 5 queries
INFO | evaluator.evaluation.phased | DB vectors shape: (20, 768)
INFO | evaluator.evaluation.phased | DB vectors stats - mean: -0.0070, std: 0.0354
INFO | evaluator.evaluation.phased | DB vectors norms - mean: 1.0000
INFO | evaluator.evaluation.phased | DB payload count: 20
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | RETRIEVAL DEBUG SAMPLE (first 3 queries):
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased |
Query 1:
INFO | evaluator.evaluation.phased |   ASR query text:        'Do mitochondria play a role in remodelling lace plant leaves during programmed cell death?'
INFO | evaluator.evaluation.phased |   Expected doc:  [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. The lace plant (Apon'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.1850 | [21645374] 'Programmed cell death (PCD) is the regulated death of cells within an organism. '
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.0919 | [25957366] 'Electronic health records have the potential to facilitate family history use by'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.0874 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0766 | [25432938] 'The objective of the current study is to determine to what extent the reduction '
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0676 | [11729377] 'To assess and compare the value of split-liver transplantation (SLT) and living-'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.1850)
INFO | evaluator.evaluation.phased |
Query 2:
INFO | evaluator.evaluation.phased |   ASR query text:        'Landolt C and snellen e acuity: differences in strabismus amblyopia?'
INFO | evaluator.evaluation.phased |   Expected doc:  [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The ability to recognize '
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✗] Score: 0.1479 | [17113061] 'Although observational data support an inverse relationship between high-density'
INFO | evaluator.evaluation.phased |     2. [✓] Score: 0.1471 | [16418930] 'Assessment of visual acuity depends on the optotypes used for measurement. The a'
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.1119 | [18239988] 'Specific markers for differentiation of nonalcoholic (NASH) from alcoholic steat'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.1015 | [25432938] 'The objective of the current study is to determine to what extent the reduction '
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0986 | [17208539] 'The transanal endorectal pull-through (TERPT) is becoming the most popular proce'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 2 (score: 0.1471)
INFO | evaluator.evaluation.phased |
Query 3:
INFO | evaluator.evaluation.phased |   ASR query text:        'Syncope during bathing in infants, a pediatric form of water-induced urticaria?'
INFO | evaluator.evaluation.phased |   Expected doc:  [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem in pediatric practi'
INFO | evaluator.evaluation.phased |   Query emb norm: 1.0000
INFO | evaluator.evaluation.phased |   Top 5 retrieved:
INFO | evaluator.evaluation.phased |     1. [✓] Score: 0.1490 | [9488747] 'Apparent life-threatening events in infants are a difficult and frequent problem'
INFO | evaluator.evaluation.phased |     2. [✗] Score: 0.0771 | [10966337] 'We evaluated the usefulness of a short stay or 23-hour ward in a pediatric unit '
INFO | evaluator.evaluation.phased |     3. [✗] Score: 0.0649 | [17208539] 'The transanal endorectal pull-through (TERPT) is becoming the most popular proce'
INFO | evaluator.evaluation.phased |     4. [✗] Score: 0.0615 | [18847643] 'Trauma patients who require therapeutic anticoagulation pose a difficult treatme'
INFO | evaluator.evaluation.phased |     5. [✗] Score: 0.0550 | [23831910] 'From March 2007 to January 2011, 88 DBE procedures were performed on 66 patients'
INFO | evaluator.evaluation.phased |   Expected doc found at rank: 1 (score: 0.1490)
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | PHASE 4: IR Metrics
INFO | evaluator.evaluation.phased | ==================================================
INFO | evaluator.evaluation.phased | Embedding alignment — cosine mean=-0.0314 std=0.0152
INFO | evaluator.evaluation.phased | IR Metrics:
INFO | evaluator.evaluation.phased |   MRR: 0.9000
INFO | evaluator.evaluation.phased |   MAP: 0.9000
INFO | evaluator.evaluation.phased |   Recall@1: 0.8000
INFO | evaluator.evaluation.phased |   NDCG@1: 0.8000
INFO | evaluator.evaluation.phased |   Recall@5: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@5: 0.9262
INFO | evaluator.evaluation.phased |   Recall@10: 1.0000
INFO | evaluator.evaluation.phased |   NDCG@10: 0.9262
INFO | evaluator.evaluation.phased | Stage latency — asr=0.0s embed=0.0s retrieve=0.0s total=0.1s
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.evaluation.phased | Cache Statistics:
INFO | evaluator.evaluation.phased |   Total size: 515.78 KB
INFO | evaluator.evaluation.phased |   Breakdown:
INFO | evaluator.evaluation.phased |     asr_features: 0.00 B (0 files)
INFO | evaluator.evaluation.phased |     transcriptions: 2.20 KB (10 files)
INFO | evaluator.evaluation.phased |     embeddings: 109.38 KB (35 files)
INFO | evaluator.evaluation.phased |     audio_embeddings: 15.62 KB (5 files)
INFO | evaluator.evaluation.phased |     vector_db: 388.58 KB (8 files)
INFO | evaluator.evaluation.phased |     checkpoints: 0.00 B (0 files)
INFO | evaluator.evaluation.phased | ============================================================
INFO | evaluator.services.model_provider | provider.shutdown offload=True

INFO | evaluator.services.model_services | service.stop label=text_embedding:labse@cpu
INFO | evaluator.services.model_services | service.stop label=audio_embedding:hubert@cpu
fusion hubert+labse (audio_w=0.7) -> {'MRR': 0.9, 'MAP': 0.9, 'Recall@1': 0.8, 'Recall@5': 1.0, 'NDCG@10': 0.9262}

,WER,CER,MRR,MAP,Recall@1,Recall@5,NDCG@10
setting,,,,,,,
whisper-tiny + labse,0.2853,0.0924,0.90,0.90,0.8,1.0,0.9262
m4t-asr + labse,0.3948,0.1075,0.90,0.90,0.8,1.0,0.9262
m4t-translate(eng) + labse,0.3948,0.1075,0.90,0.90,0.8,1.0,0.9262
m4t + dense,0.3948,0.1075,0.90,0.90,0.8,1.0,0.9262
m4t + hybrid(rrf),0.3948,0.1075,0.84,0.84,0.8,1.0,0.8774
m4t + dense + reranker,0.3948,0.1075,1.00,1.00,1.0,1.0,1.0000
fusion hubert+labse (audio_w=0.3),NaN,NaN,1.00,1.00,1.0,1.0,1.0000
fusion hubert+labse (audio_w=0.5),NaN,NaN,1.00,1.00,1.0,1.0,1.0000
fusion hubert+labse (audio_w=0.7),NaN,NaN,0.90,0.90,0.8,1.0,0.9262

## 7. Experiment D — SONAR shared-space retrieval

SONAR's speech and text encoders (the embedding side of the Seamless/M4T family) share one
**1024-d space**, so an **audio query** can retrieve a **text corpus** directly — zero-shot,
no trained head and no fusion. This is the M4T/SONAR cross-modal setting
(`audio_text_retrieval` with `sonar_speech` query encoder + `sonar` text encoder).

> Requires `pip install -e '..[sonar]'` (pulls sonar-space + fairseq2). Gated by `RUN_SONAR`.

In [4]:
RUN_SONAR = True  # set True after: pip install -e '..[sonar]'
if RUN_SONAR:
    run_setting(
        'sonar cross-modal (audio->text)',
        {'asr_model_type': None,
         'audio_emb_model_type': 'sonar_speech', 'audio_emb_model_name': 'sonar_speech_encoder_eng',
         'audio_emb_dim': 1024, 'text_emb_model_type': 'sonar'},
        mode='audio_text_retrieval',
        features={'embedding_fusion': {'enabled': False}},  # shared space -> compare directly
    )
    display(pd.DataFrame(ROWS).set_index('setting'))
else:
    print('RUN_SONAR=False - install evaluator[sonar] and set RUN_SONAR=True to run SONAR cross-modal retrieval.')

INFO | evaluator | Logging initialized. Log file: logs/2026-06-03_22-48-50_sonar cross-modal (audio->text).log
INFO | evaluator.services.model_provider | provider.shutdown offload=True

EvaluationError: Failed to create pipelines: SONAR not installed. Install with: pip install 'evaluator[sonar]'
(pulls sonar-space + fairseq2).

In [5]:
!pip freeze | grep fairseq
!pip freeze | grep sonar

fairseq2==0.8.1
fairseq2n==0.8.1
sonar-space==0.5.0

## 8. Summary

All settings side by side, with an MRR bar chart.

In [6]:
import matplotlib.pyplot as plt

df = pd.DataFrame(ROWS).set_index('setting')
display(df)

if 'MRR' in df.columns:
    ax = df['MRR'].plot(kind='barh', figsize=(8, 0.5 * len(df) + 1), color='#1d4ed8')
    ax.set_xlabel('MRR'); ax.set_title('Retrieval quality (MRR) by setting')
    plt.tight_layout(); plt.show()

KeyError: "None of ['setting'] are in the columns"

## 9. Scaling up

- **More data / rigor:** raise `TRACE_LIMIT` (full bundled set = 20) or point `Q`/`C` at
  `data/pubmedqa/` (larger) or your own `questions.json` / `corpus.json`.
- **GPU:** set `DEVICE = 'cuda:0'` for much faster M4T.
- **Non-English audio:** set per-question `language` in the dataset (or `audio_synthesis.language`)
  and use `m4t-translate(eng)` to retrieve foreign-language speech against an English corpus.
- **Matrix runs:** `from evaluator import run_evaluation_matrix` to sweep many setups over one
  base config in a single call.
- **SONAR cross-modal:** `pip install -e '..[sonar]'` then set `RUN_SONAR = True` above for
  zero-shot audio→text retrieval in the shared SONAR space.